name: Run Geckodriver Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Geckodriver and Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        chmod +x ./drivers/geckodriver

    - name: Verify Firefox version
      run: firefox --version

    - name: Verify Geckodriver version
      run: ./drivers/geckodriver --version

    - name: Run script
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GECKODRIVER_PATH: ./drivers/geckodriver
      run: python script.py
