name: Claim Rewards Automation

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam sekali
  workflow_dispatch:      # Memungkinkan trigger manual

jobs:
  claim-rewards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install selenium requests

      - name: Download Geckodriver
        run: |
          wget -q -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run Claim Script
        run: python script.py
