name: Test Automation

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        wget $CHROMEDRIVER_URL -O chromedriver.zip
        unzip -o chromedriver.zip -d ./drivers/
        rm chromedriver.zip
        chmod +x ./drivers/chromedriver

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: python script.py
