name: Automation Workflow

on:
  push:
    branches:
      - main

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y wget unzip

    - name: Set up ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
        unzip -o chromedriver.zip -d ./drivers/
        chmod +x ./drivers/chromedriver
        rm chromedriver.zip

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Run Python Script
      run: python script.py
