name: Claim Rewards Workflow

on:
  schedule:
    - cron: '0 */3 * * *'  # Menjadwalkan tugas setiap 3 jam sekali
  workflow_dispatch:  # memungkinkan Anda untuk menjalankan secara manual

jobs:
  claim_rewards:
    runs-on: ubuntu-latest  # Menjalankan di mesin Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Menggunakan Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pastikan Anda memiliki file requirements.txt

    - name: Install Selenium and Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-geckodriver
        sudo apt-get install -y libgdk-pixbuf2.0-0

    - name: Run Claim Rewards Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        DATA_JSON: ${{ secrets.DATA_JSON }}  # Anda bisa menyimpan kredensial di Secrets GitHub
      run: |
        python main.py  # Pastikan `main.py` adalah nama skrip utama Anda
