name: Auto Claim Rewards

on:
  schedule:
    - cron: "0 */3 * * *"  # Jalankan setiap 3 jam
  workflow_dispatch:

jobs:
  claim_rewards:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium python-telegram-bot python-dotenv requests

    - name: Download and Setup Geckodriver
      run: |
        wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz" -O geckodriver.tar.gz
        tar -xzf geckodriver.tar.gz -C ./drivers
        chmod +x ./drivers/geckodriver

    - name: Run Claim Script
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DATA_JSON: ${{ secrets.DATA_JSON }}
      run: python script.py
