name: Claim Rewards Automation

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam sekali
  workflow_dispatch:      # Memungkinkan trigger manual

jobs:
  claim-rewards:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Langkah 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Sesuaikan dengan versi Python yang Anda gunakan

    # Langkah 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pastikan Anda memiliki file `requirements.txt` yang berisi semua dependensi (termasuk Selenium)

    # Langkah 4: Download GeckoDriver
    - name: Download GeckoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
        mkdir -p drivers
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz -C drivers
        chmod +x drivers/geckodriver

    # Langkah 5: Jalankan skrip Python
    - name: Run Claim Script
      run: python script.py
